# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: stevenryregistry-microsoft.azurecr.io
  tag: latest
  pullPolicy: Always
  repoCredsSecretName: myregistrykey


mongo:
  collection: bikes
  connectionString: <insert connection string here>
